/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedBuscarRouteImport } from './routes/_authed/buscar'
import { Route as CompartidoTokenRouteImport } from './routes/compartido.$token'
import { Route as AuthedAdministracionIndexRouteImport } from './routes/_authed/administracion/index'
import { Route as AuthedAuditoriaIndexRouteImport } from './routes/_authed/auditoria/index'
import { Route as AuthedDocumentosIndexRouteImport } from './routes/_authed/documentos/index'
import { Route as AuthedDocumentosFolderIdRouteImport } from './routes/_authed/documentos/$folderId'
import { Route as AuthedDocumentosPapeleraRouteImport } from './routes/_authed/documentos/papelera'
import { Route as ApiImagenesSplatRouteImport } from './routes/api/imagenes/$'
import { Route as AuthedDocumentosDocDocIdRouteImport } from './routes/_authed/documentos/doc/$docId'
import { Route as ApiCarpetasFolderIdZipRouteImport } from './routes/api/carpetas/$folderId/zip'
import { Route as ApiCompartidoTokenPdfRouteImport } from './routes/api/compartido/$token/pdf'
import { Route as ApiDocumentosDocIdPdfRouteImport } from './routes/api/documentos/$docId/pdf'
import { Route as ApiDocumentosDocIdWordRouteImport } from './routes/api/documentos/$docId/word'
import { Route as ApiCompartidoTokenImagenesSplatRouteImport } from './routes/api/compartido/$token/imagenes/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedBuscarRoute = AuthedBuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => AuthedRoute,
} as any)
const CompartidoTokenRoute = CompartidoTokenRouteImport.update({
  id: '/compartido/$token',
  path: '/compartido/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAdministracionIndexRoute =
  AuthedAdministracionIndexRouteImport.update({
    id: '/administracion/',
    path: '/administracion/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAuditoriaIndexRoute = AuthedAuditoriaIndexRouteImport.update({
  id: '/auditoria/',
  path: '/auditoria/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDocumentosIndexRoute = AuthedDocumentosIndexRouteImport.update({
  id: '/documentos/',
  path: '/documentos/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDocumentosFolderIdRoute =
  AuthedDocumentosFolderIdRouteImport.update({
    id: '/documentos/$folderId',
    path: '/documentos/$folderId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedDocumentosPapeleraRoute =
  AuthedDocumentosPapeleraRouteImport.update({
    id: '/documentos/papelera',
    path: '/documentos/papelera',
    getParentRoute: () => AuthedRoute,
  } as any)
const ApiImagenesSplatRoute = ApiImagenesSplatRouteImport.update({
  id: '/api/imagenes/$',
  path: '/api/imagenes/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDocumentosDocDocIdRoute =
  AuthedDocumentosDocDocIdRouteImport.update({
    id: '/documentos/doc/$docId',
    path: '/documentos/doc/$docId',
    getParentRoute: () => AuthedRoute,
  } as any)
const ApiCarpetasFolderIdZipRoute = ApiCarpetasFolderIdZipRouteImport.update({
  id: '/api/carpetas/$folderId/zip',
  path: '/api/carpetas/$folderId/zip',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompartidoTokenPdfRoute = ApiCompartidoTokenPdfRouteImport.update({
  id: '/api/compartido/$token/pdf',
  path: '/api/compartido/$token/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentosDocIdPdfRoute = ApiDocumentosDocIdPdfRouteImport.update({
  id: '/api/documentos/$docId/pdf',
  path: '/api/documentos/$docId/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentosDocIdWordRoute = ApiDocumentosDocIdWordRouteImport.update({
  id: '/api/documentos/$docId/word',
  path: '/api/documentos/$docId/word',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompartidoTokenImagenesSplatRoute =
  ApiCompartidoTokenImagenesSplatRouteImport.update({
    id: '/api/compartido/$token/imagenes/$',
    path: '/api/compartido/$token/imagenes/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/buscar': typeof AuthedBuscarRoute
  '/compartido/$token': typeof CompartidoTokenRoute
  '/documentos/$folderId': typeof AuthedDocumentosFolderIdRoute
  '/documentos/papelera': typeof AuthedDocumentosPapeleraRoute
  '/api/imagenes/$': typeof ApiImagenesSplatRoute
  '/administracion/': typeof AuthedAdministracionIndexRoute
  '/auditoria/': typeof AuthedAuditoriaIndexRoute
  '/documentos/': typeof AuthedDocumentosIndexRoute
  '/documentos/doc/$docId': typeof AuthedDocumentosDocDocIdRoute
  '/api/carpetas/$folderId/zip': typeof ApiCarpetasFolderIdZipRoute
  '/api/compartido/$token/pdf': typeof ApiCompartidoTokenPdfRoute
  '/api/documentos/$docId/pdf': typeof ApiDocumentosDocIdPdfRoute
  '/api/documentos/$docId/word': typeof ApiDocumentosDocIdWordRoute
  '/api/compartido/$token/imagenes/$': typeof ApiCompartidoTokenImagenesSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/buscar': typeof AuthedBuscarRoute
  '/compartido/$token': typeof CompartidoTokenRoute
  '/documentos/$folderId': typeof AuthedDocumentosFolderIdRoute
  '/documentos/papelera': typeof AuthedDocumentosPapeleraRoute
  '/api/imagenes/$': typeof ApiImagenesSplatRoute
  '/administracion': typeof AuthedAdministracionIndexRoute
  '/auditoria': typeof AuthedAuditoriaIndexRoute
  '/documentos': typeof AuthedDocumentosIndexRoute
  '/documentos/doc/$docId': typeof AuthedDocumentosDocDocIdRoute
  '/api/carpetas/$folderId/zip': typeof ApiCarpetasFolderIdZipRoute
  '/api/compartido/$token/pdf': typeof ApiCompartidoTokenPdfRoute
  '/api/documentos/$docId/pdf': typeof ApiDocumentosDocIdPdfRoute
  '/api/documentos/$docId/word': typeof ApiDocumentosDocIdWordRoute
  '/api/compartido/$token/imagenes/$': typeof ApiCompartidoTokenImagenesSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/buscar': typeof AuthedBuscarRoute
  '/compartido/$token': typeof CompartidoTokenRoute
  '/_authed/documentos/$folderId': typeof AuthedDocumentosFolderIdRoute
  '/_authed/documentos/papelera': typeof AuthedDocumentosPapeleraRoute
  '/api/imagenes/$': typeof ApiImagenesSplatRoute
  '/_authed/administracion/': typeof AuthedAdministracionIndexRoute
  '/_authed/auditoria/': typeof AuthedAuditoriaIndexRoute
  '/_authed/documentos/': typeof AuthedDocumentosIndexRoute
  '/_authed/documentos/doc/$docId': typeof AuthedDocumentosDocDocIdRoute
  '/api/carpetas/$folderId/zip': typeof ApiCarpetasFolderIdZipRoute
  '/api/compartido/$token/pdf': typeof ApiCompartidoTokenPdfRoute
  '/api/documentos/$docId/pdf': typeof ApiDocumentosDocIdPdfRoute
  '/api/documentos/$docId/word': typeof ApiDocumentosDocIdWordRoute
  '/api/compartido/$token/imagenes/$': typeof ApiCompartidoTokenImagenesSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/buscar'
    | '/compartido/$token'
    | '/documentos/$folderId'
    | '/documentos/papelera'
    | '/api/imagenes/$'
    | '/administracion/'
    | '/auditoria/'
    | '/documentos/'
    | '/documentos/doc/$docId'
    | '/api/carpetas/$folderId/zip'
    | '/api/compartido/$token/pdf'
    | '/api/documentos/$docId/pdf'
    | '/api/documentos/$docId/word'
    | '/api/compartido/$token/imagenes/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/buscar'
    | '/compartido/$token'
    | '/documentos/$folderId'
    | '/documentos/papelera'
    | '/api/imagenes/$'
    | '/administracion'
    | '/auditoria'
    | '/documentos'
    | '/documentos/doc/$docId'
    | '/api/carpetas/$folderId/zip'
    | '/api/compartido/$token/pdf'
    | '/api/documentos/$docId/pdf'
    | '/api/documentos/$docId/word'
    | '/api/compartido/$token/imagenes/$'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/buscar'
    | '/compartido/$token'
    | '/_authed/documentos/$folderId'
    | '/_authed/documentos/papelera'
    | '/api/imagenes/$'
    | '/_authed/administracion/'
    | '/_authed/auditoria/'
    | '/_authed/documentos/'
    | '/_authed/documentos/doc/$docId'
    | '/api/carpetas/$folderId/zip'
    | '/api/compartido/$token/pdf'
    | '/api/documentos/$docId/pdf'
    | '/api/documentos/$docId/word'
    | '/api/compartido/$token/imagenes/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  CompartidoTokenRoute: typeof CompartidoTokenRoute
  ApiImagenesSplatRoute: typeof ApiImagenesSplatRoute
  ApiCarpetasFolderIdZipRoute: typeof ApiCarpetasFolderIdZipRoute
  ApiCompartidoTokenPdfRoute: typeof ApiCompartidoTokenPdfRoute
  ApiDocumentosDocIdPdfRoute: typeof ApiDocumentosDocIdPdfRoute
  ApiDocumentosDocIdWordRoute: typeof ApiDocumentosDocIdWordRoute
  ApiCompartidoTokenImagenesSplatRoute: typeof ApiCompartidoTokenImagenesSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/buscar': {
      id: '/_authed/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof AuthedBuscarRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/compartido/$token': {
      id: '/compartido/$token'
      path: '/compartido/$token'
      fullPath: '/compartido/$token'
      preLoaderRoute: typeof CompartidoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/administracion/': {
      id: '/_authed/administracion/'
      path: '/administracion'
      fullPath: '/administracion/'
      preLoaderRoute: typeof AuthedAdministracionIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/auditoria/': {
      id: '/_authed/auditoria/'
      path: '/auditoria'
      fullPath: '/auditoria/'
      preLoaderRoute: typeof AuthedAuditoriaIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/documentos/': {
      id: '/_authed/documentos/'
      path: '/documentos'
      fullPath: '/documentos/'
      preLoaderRoute: typeof AuthedDocumentosIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/documentos/$folderId': {
      id: '/_authed/documentos/$folderId'
      path: '/documentos/$folderId'
      fullPath: '/documentos/$folderId'
      preLoaderRoute: typeof AuthedDocumentosFolderIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/documentos/papelera': {
      id: '/_authed/documentos/papelera'
      path: '/documentos/papelera'
      fullPath: '/documentos/papelera'
      preLoaderRoute: typeof AuthedDocumentosPapeleraRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/imagenes/$': {
      id: '/api/imagenes/$'
      path: '/api/imagenes/$'
      fullPath: '/api/imagenes/$'
      preLoaderRoute: typeof ApiImagenesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/documentos/doc/$docId': {
      id: '/_authed/documentos/doc/$docId'
      path: '/documentos/doc/$docId'
      fullPath: '/documentos/doc/$docId'
      preLoaderRoute: typeof AuthedDocumentosDocDocIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/carpetas/$folderId/zip': {
      id: '/api/carpetas/$folderId/zip'
      path: '/api/carpetas/$folderId/zip'
      fullPath: '/api/carpetas/$folderId/zip'
      preLoaderRoute: typeof ApiCarpetasFolderIdZipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/compartido/$token/pdf': {
      id: '/api/compartido/$token/pdf'
      path: '/api/compartido/$token/pdf'
      fullPath: '/api/compartido/$token/pdf'
      preLoaderRoute: typeof ApiCompartidoTokenPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documentos/$docId/pdf': {
      id: '/api/documentos/$docId/pdf'
      path: '/api/documentos/$docId/pdf'
      fullPath: '/api/documentos/$docId/pdf'
      preLoaderRoute: typeof ApiDocumentosDocIdPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documentos/$docId/word': {
      id: '/api/documentos/$docId/word'
      path: '/api/documentos/$docId/word'
      fullPath: '/api/documentos/$docId/word'
      preLoaderRoute: typeof ApiDocumentosDocIdWordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/compartido/$token/imagenes/$': {
      id: '/api/compartido/$token/imagenes/$'
      path: '/api/compartido/$token/imagenes/$'
      fullPath: '/api/compartido/$token/imagenes/$'
      preLoaderRoute: typeof ApiCompartidoTokenImagenesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedBuscarRoute: typeof AuthedBuscarRoute
  AuthedDocumentosFolderIdRoute: typeof AuthedDocumentosFolderIdRoute
  AuthedDocumentosPapeleraRoute: typeof AuthedDocumentosPapeleraRoute
  AuthedAdministracionIndexRoute: typeof AuthedAdministracionIndexRoute
  AuthedAuditoriaIndexRoute: typeof AuthedAuditoriaIndexRoute
  AuthedDocumentosIndexRoute: typeof AuthedDocumentosIndexRoute
  AuthedDocumentosDocDocIdRoute: typeof AuthedDocumentosDocDocIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedBuscarRoute: AuthedBuscarRoute,
  AuthedDocumentosFolderIdRoute: AuthedDocumentosFolderIdRoute,
  AuthedDocumentosPapeleraRoute: AuthedDocumentosPapeleraRoute,
  AuthedAdministracionIndexRoute: AuthedAdministracionIndexRoute,
  AuthedAuditoriaIndexRoute: AuthedAuditoriaIndexRoute,
  AuthedDocumentosIndexRoute: AuthedDocumentosIndexRoute,
  AuthedDocumentosDocDocIdRoute: AuthedDocumentosDocDocIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  CompartidoTokenRoute: CompartidoTokenRoute,
  ApiImagenesSplatRoute: ApiImagenesSplatRoute,
  ApiCarpetasFolderIdZipRoute: ApiCarpetasFolderIdZipRoute,
  ApiCompartidoTokenPdfRoute: ApiCompartidoTokenPdfRoute,
  ApiDocumentosDocIdPdfRoute: ApiDocumentosDocIdPdfRoute,
  ApiDocumentosDocIdWordRoute: ApiDocumentosDocIdWordRoute,
  ApiCompartidoTokenImagenesSplatRoute: ApiCompartidoTokenImagenesSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
